version: "3"

services: 
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh index.js 
    networks: 
      - "node-net"
    volumes: 
      - /usr/src/app/node_modules
      - ./node:/usr/src/app
    depends_on: 
      - db
    ports:
      - "3000:3000"
  
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    ports: 
      - "8080:8080"
    networks: 
      - "node-net"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
        - ./mysql/init:/docker-entrypoint-initdb.d/:ro
        - ./mysql/data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=node_app
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - "node-net"

networks: 
  node-net:
    driver: bridge
